pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    environment {
        DOCKER_IMAGE = "krishna1084/sampleapp:1.0"
    }

    stages {

        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/krishnapatel-dev/cloud-native-cicd-kubernetes-pipeline.git'
            }
        }

        stage('Build App') {
            steps {
                bat 'cd app && "C:\\Maven\\apache-maven-3.9.14\\bin\\mvn" clean package'
            }
        }

        stage('Docker Build & Push') {
            steps {
                bat 'docker build -t %DOCKER_IMAGE% .'

                withCredentials([usernamePassword(credentialsId: 'docker-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    bat 'docker login -u %USER% -p %PASS%'
                }

                bat 'docker push %DOCKER_IMAGE%'
            }
}

        stage('Deploy to Kubernetes') {
            steps {
                bat 'kubectl apply -f k8s/deployment.yaml'
                bat 'kubectl apply -f k8s/service.yaml'
            }
        }
    }
}