pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "krishna1084/sampleapp:1.0"
    }

    stages {

        stage('Clone Repo') {
            steps {
                git 'https://github.com/krishnapatel-dev/cloud-native-cicd-kubernetes-pipeline.git'
            }
        }

        stage('Build App') {
            steps {
                sh 'cd app && mvn clean package'
            }
        }

        stage('Docker Build & Push') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
                sh 'docker push $DOCKER_IMAGE'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/deployment.yaml'
                sh 'kubectl apply -f k8s/service.yaml'
            }
        }
    }
}